version: "3.1"
services:
  db:
    image: mariadb:10.4
    container_name: mvc-mariadb
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_DATABASE=db
      - MYSQL_USER=df_usr
      - MYSQL_PASSWORD=S3cret
      - TZ=Europe/Rome
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+02:00', '--max_allowed_packet=134217728' ]
    ports:
      - "3306:3306"

  php:
    build: docker/php
    container_name: mvc-php
    volumes:
      - ./docker/php/000-default.dev.conf:/etc/apache2/sites-available/000-default.conf
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/base.ini
    ports:
      - '80:80'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mvc_db
    depends_on:
      - db
