version: "3.1"
services:
  db:
    image: mariadb:10.4
    container_name: stands-mariadb
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
      - MYSQL_DATABASE=stands
      - MYSQL_USER=df_usr
      - MYSQL_PASSWORD=${MYSQL_PWD}
      - TZ=Europe/Rome
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+02:00', '--max_allowed_packet=134217728' ]
    ports:
      - "3306:3306"

  php:
    build: docker/php
    container_name: stands-php
    volumes:
      - ./docker/php/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - /etc/letsencrypt/live/stands.master-attivazioni.it/fullchain.pem:/etc/ssl/certs/mgstands-fullchain.pem
      - /etc/letsencrypt/live/stands.master-attivazioni.it/privkey.pem:/etc/ssl/certs/mgstands-privkey.pem
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/base.ini
    ports:
      - '80:80'
      - '443:443'
